// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUzekMRIzpbn3vVvxlTcPe6EpIVD_ZDAs',
    appId: '1:1074044586953:android:d0c36cbb2bb49e240df618',
    messagingSenderId: '1074044586953',
    projectId: 'ecommerceapp-304a9',
    storageBucket: 'ecommerceapp-304a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDri0bSHs4hvmGtFx7NMGHJx5a7333sQEQ',
    appId: '1:1074044586953:ios:320e3dcf7dcae8140df618',
    messagingSenderId: '1074044586953',
    projectId: 'ecommerceapp-304a9',
    storageBucket: 'ecommerceapp-304a9.firebasestorage.app',
    androidClientId: '1074044586953-9ef1r8eip4or7tsceofsdd8dnnumpnvl.apps.googleusercontent.com',
    iosClientId: '1074044586953-kpp84uhne3kukoqcm1oe1j9lunr9vang.apps.googleusercontent.com',
    iosBundleId: 'com.example.khyberKart',
  );

}